name: Docker Image Publishing

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*.*.*

  # Run tests for any PRs.
  pull_request:

  schedule:
    - cron: '0 6 * * *'

env:
  IMAGE_NAME: "readis"

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        registry:
          - docker
          - github

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --pull -f ./.docker/Dockerfile -t "${{ env.IMAGE_NAME }}" ./.docker

      - name: Log into Docker Hub
        if: matrix.registry == 'docker' && (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/tags'))
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ github.actor }}" --password-stdin

      - name: Log into GitHub container registry
        if: matrix.registry == 'github' && (startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/tags'))
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Determine image identifier for Docker Hub
        if: matrix.registry == 'docker'
        run: echo "IMAGE_ID=${{ github.actor }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Determine image identifier for GitHub container registry
        if: matrix.registry == 'github'
        run: echo "IMAGE_ID=ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Normalize image identifier
        run: echo "NORMALIZED_IMAGE_ID=$(echo ${{ env.IMAGE_ID}} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Push latest image
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          echo "IMAGE_ID: ${{ env.NORMALIZED_IMAGE_ID }}"
          echo "VERSION: latest"

          docker tag "${{ env.IMAGE_NAME }}" "${{ env.NORMALIZED_IMAGE_ID }}:latest"
          docker push "${{ env.MORMALIZED_IMAGE_ID }}"

      - name: Push release image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Determine tag
          TAG=$(git describe --exact-match --tags 2> /dev/null | sed -e s/v//g)
          MAJOR=$(echo ${TAG} | cut -d'.' -f1)
          FEATURE=${MAJOR}.$(echo ${TAG} | cut -d'.' -f2)

          echo "IMAGE_ID: ${{ env.NORMALIZED_IMAGE_ID }}"
          echo "VERSION: ${TAG}"

          docker tag "${{ env.IMAGE_NAME }}" "${{ env.NORMALIZED_IMAGE_ID }}:latest"
          docker tag "${{ env.IMAGE_NAME }}" "${{ env.NORMALIZED_IMAGE_ID }}:${TAG}"
          docker tag "${{ env.IMAGE_NAME }}" "${{ env.NORMALIZED_IMAGE_ID }}:${MAJOR}"
          docker tag "${{ env.IMAGE_NAME }}" "${{ env.NORMALIZED_IMAGE_ID }}:${FEATURE}"
          docker push "${{ env.IMAGE_ID }}"

  release:
    needs:
      - push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version
        id: data
        run: |
          # Strip git ref prefix from version
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/^v//')

          echo $RELEASE_VERSION
          echo "##[set-output name=version;]$RELEASE_VERSION"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Version ${{ steps.data.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
